auto: true
title: "FREEBASSEL"
permalink: /:categories/:title/
exclude: README.md, designs

description: "#FREEBASSEL is a campaign to bring about the safe and immediate release of Bassel Khartabil from wrongful detainment in Syria since March 2012. He is a well known contributor to global software and culture communities like Creative Commons, Mozilla Firefox, Wikipedia, Open Clip Art Library, Fabricatorz, and Sharism. He is missed by these communities, his family, friends and loved ones. The campaign says, We will not stop campaigning for him until we see him as a free global citizen once again."

keywords: ['freebassel', 'basselkhartabil ', 'basselsafadi', 'bassel', 'syria', 'damascus', 'creativecommons', 'freeculture', 'sharing', 'sharism']

languages :
  en: English
  ar: Arabic
